autoMigrate: true
log: debug

server:
  http: 0.0.0.0:8888
  prefix: ""

proxy:
- name: db1
  desc: db1 for 1
  storage:
    type: postgres
    config:
      host: localhost
      port: 5432
      database: makabaka
      user: makabaka
      password: makabaka
      debug: true
      ssl:
        mode: disable
